spring.application.name=PAYMENT_SERVICE
server.port=8082


# FIXED: Changed protocol to postgresql and port to 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_service
spring.datasource.username=postgres
spring.datasource.password=sasic
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


razorpay.key.id=rzp_test_T5qhxCaQM4vu34
razorpay.key.secret=V8kQeMYfQRKqjn07vRYFpV5q
razorpay.webhook.secret=something
